//Create Customer Records
    let Customers = [
            {name:"Jeremy",
            email:"Jeremy@verizon.net",
            purchases:["Chair", "Table", "Bed"]},
            {name:"Warren",
            email:"WWsatkins@verizon.net",
            purchases:["Flag", "Plate", "Bowl"]},
            {name:"Elijah",
            email:"Epollock@verizon.net",
            purchases:["Fork", "Knife", "Spoon"]},];
        console.log(Customers);
//Create Customer Records
   Customers.push({
    name:"Anabelle",
    email:"Afait@verizon.net",
    purchases:["Phone", "Charger", "Airpods"]
   });
   Customers.shift();
   console.log(customers);